x1 = int(input("Enter x1 : "))
x2 = int(input("Enter x2 : "))
y1 = int(input("Enter y1 : "))
y2 = int(input("Enter y2 : "))
d = (((x2-x1)**2 + (y2-y1)**2)**0.5)
print("Distance between points is d = ",d)
